name: Check for Version up
on:
  # note: make disabled
  # schedule:
  #   - cron: '*/10 * * * *'
env:
  INTERVEL_SEC: 600 # same to cron interval
  TARGET_PATH: src
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check for updates
        id: check
        run: |
          LATEST_COMMIT=$((git log -1 -- ${{ env.TARGET_PATH }}))
          echo "Latest Commit: $LATEST_COMMIT"
          LATEST_COMMIT_UNIX_TIME=$(git log -1 --format=%ct -- src)
          CUREENT_TIME=$(date +%s)
          echo "Latest: $LATEST_COMMIT_UNIX_TIME"
          echo "Current: $CUREENT_TIME"
          DIFF=$((CUREENT_TIME - LATEST_COMMIT_UNIX_TIME))
          echo "Diff: $DIFF"
          echo "interval: ${{ env.INTERVEL_SEC }}"
          IS_EXIST_NEW_COMMIT=$((CUREENT_TIME - ${{ env.INTERVEL_SEC }} - $LATEST_COMMIT_UNIX_TIME < 0))
          echo "Is exist new commit?: $IS_EXIST_NEW_COMMIT"
          echo "is_exist_new_commit=$IS_EXIST_NEW_COMMIT" >> $GITHUB_OUTPUT
      - name: if check flag is true, request to update
        if: ${{ steps.check.outputs.is_exist_new_commit != '0' }}
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: linnefromice
          repo: sandbox-rust-release-by-ci
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_file_name: release.yml


