name: Sample
on:
  push:
    branches:
      - main
jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run cargo release
        run: |
          LATEST_COMMIT=$(git log -1 -- src)
          ls -la
          echo "Latest Commit: $LATEST_COMMIT"
          LATEST_COMMIT_UNIX_TIME=$(git log -1 --format=%ct -- src)
          CUREENT_TIME=$(date +%s)
          echo "Latest: $LATEST_COMMIT_UNIX_TIME"
          echo "Current: $CUREENT_TIME"
          DIFF=$((CUREENT_TIME - $LATEST_COMMIT_UNIX_TIME))
          echo "Diff: $DIFF"
          IS_EXIST_NEW_COMMIT=$((CUREENT_TIME - 3600 - $LATEST_COMMIT_UNIX_TIME < 0))
          echo "Is exist new commit?: $IS_EXIST_NEW_COMMIT"
